# Generated by Django 3.2.6 on 2021-08-13 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('pict', models.ImageField(upload_to='')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.bucket')),
            ],
        ),
    ]
